FROM golang:1.25.6-alpine3.22 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download -x

COPY . .
RUN CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags "-s -w" \
    -o /bin/bot \
    ./cmd/bot

FROM alpine:3.22

RUN adduser -D -u 10001 appuser
USER appuser

COPY --from=builder /bin/bot /app/bot

WORKDIR /app

ENTRYPOINT ["/app/bot"]